### ISSUE TITLE
Cannot start Zookeeper container

### ISSUE THREAD

**Issue by arun-gupta** [fabric8io/fabric8-zookeeper-docker#5]
Starting the container as `docker run fabric8/zookeeper` gives the following error:

```
Status: Downloaded newer image for fabric8/zookeeper:latest
JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
2015-05-20 21:14:00,118 [myid:] - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /opt/zookeeper/bin/../conf/zoo.cfg
2015-05-20 21:14:00,122 [myid:] - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /opt/zookeeper/bin/../conf/zoo.cfg
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:123)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:504)
    at java.lang.Integer.parseInt(Integer.java:527)
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:145)
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:119)
    ... 2 more
Invalid config, exiting abnormally
```

**Comment by iocanel** [comment]
The image requires some env variables to be set, in order to setup a zookeeper ensemble,
 I am not sure if this was ever working as a standalone server if no env vars were specified, but we should fix that.

You could try the setup-ensemble.sh script as shown here: https://github.com/fabric8io/fabric8-zookeeper-docker/blob/master/README.md

**Comment by iocanel** [comment]
By the way the image was created to support the fabric8 zookeeper app for kubernetes, but AFAIR this has been broken past v1beta1.

**Comment by arun-gupta** [comment]
I was hoping a one stop image, with lots of defaults and no configuration required. Is that a target for this image?

**Comment by iocanel** [comment]
The initial goal was to support "clustered" deployments, but it should be trivial to have it default to "standalone" mode. 

Let me have a look

**Comment by arun-gupta** [comment]
Thanks, will be watching this space.

**Comment by iocanel** [comment]
During the weekend, I applied one pull request that simplifies ensemble handling. On top of that I added as default behaviour to work in standalone mode. So now we have an image that can work in standalone and kubernetes mode.

Please let me know how that works for you, while I'll am updating the docs.
